version: '3.7'
services:
  robotframework:
    build: .
    volumes:
      - "./robots:/robotframework/robots"
      - "./:/robotframework"
    environment:
      - ROBOT_TESTS=/rotbotframework/robots/
      - BROWSER=firefox
